[project]
name = "docling-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.3.1",
    "fastapi[standard]>=0.115.4",
]
